### PR TITLE
Add custom cipher support

### PR DESCRIPTION
**Pull request by igramic**
https://rubygems.org/gems/foreman_scap_client/versions/0.4.7 has option for selecting ciphers.

This pull request:

- Adds :ciphers: in configuration file

- Creates foreman_scap_client_ciphers variable to select ciphers

- Updates README

### CODE REVIEW

**Comment by xprazak2** [comment]
Awesome work, needs a small change though. `foreman_scap_client_ciphers` needs to be added into defaults/main.yml so that foreman is able to detect it when importing variables.

Could you also change commit message to "Fixes #30453 - ${description}"? I have created a [redmine ticket](https://projects.theforeman.org/issues/30453) to keep track of this feature.

**Comment by igramic** [comment]
@xprazak2 variable is added and condition is changed. Let me know if anything else is needed

**Comment by xprazak2** [comment]
Thanks, it will need one small change though. Ansible/python adds [special escaping](https://stackoverflow.com/questions/41521138/ansible-template-adds-u-to-array-in-template) to strings in array:

ciphers-result


`{{ foreman_scap_client_ciphers | to_json }}` removes the escaping for me.

**Comment by xprazak2** [comment]
I squashed the commits and merged as [3707cb7](https://github.com/theforeman/ansible-foreman_scap_client/commit/3707cb7964ffe828352a620905f63b4923d362fd), thanks!

**Pull request closed without merging**
